spring:
  application:
    name: Bootcamp24
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 50
    open-in-view: false
  datasource:
    url: jdbc:h2:mem:bootcamp24;
    driverClassName: org.h2.Driver
    username: Sa1ZeR
    password:


cdr:
  file-name: cdr.txt
